In [5]:
%matplotlib widget #does interactive plotting 
import matplotlib.pyplot as plt
import numpy 
from interactive_modelstreams import plot_tidalstreams, zoom, plot_colormap, test_cocoon, test_stream
from clusterorbits import plot_sat_cluster
from galpy.orbit import Orbit
from galpy.potential import HernquistPotential
from astropy import units

# Import orbits for Milky Way's satellite galaxies
satellite_gal = Orbit.from_name('MWsatellitegalaxies') #list of satellite galaxies of Milky Way 
name_satellite_gal = satellite_gal.name

After each satellite galaxy's tidal streams are plotted and test_cocoon + test_stream are both run on simulations, notes on the presence of a cocoon and if present, how well the cocoon matches expectations (based on GD-1) have been added in text below each code block. 

In [7]:
#Defining global properties for all 14 satellite galaxy simulations 

xaxis = 't'
yaxis = 'r'
Msat = 10.**11.*units.Msun
size = 1.05*(Msat/(10.**8./1*units.Msun))**0.5*units.kpc
potential = HernquistPotential(amp = 2*Msat, a = size, ro = 8., vo=220.)
x,y,z = 4*units.kpc, 0*units.kpc, 0*units.kpc
vcirc = potential.vcirc(4*units.kpc)
vx, vy, vz = 0.*units.km/units.s, vcirc, 0.*units.km/units.s
#tform, tsteady = 7.*units.Gyr, 0.5*units.Gyr 
    #timescale for tidal disruption of satellite galaxy
Mcluster = 2e4*units.Msun

index_list = [1,5,8,10,13,26,27,28,29,30,35,37,38,39]
tsteady = 0.5*units.Gyr

# Define dictionaries for tform, unbound time, xlim, ylim, pre_tform and post_tform for all 14 satellite galaxies

tform_dict = {'BootesI': 6.*units.Gyr, 'Carina': 5.*units.Gyr,'ComaBerenices': 6.*units.Gyr,  'Draco': 0.*units.Gyr,\
              'Fornax': 8.*units.Gyr, 'ReticulumII': 2.*units.Gyr, 'Sgr': 4.*units.Gyr, 'Sculptor': 5.*units.Gyr,\
              'Segue1': 2.*units.Gyr, 'Segue2': 1.5*units.Gyr, 'TucanaIII': -3.*units.Gyr, 'UrsaMajorII': 6.5*units.Gyr,\
              'UrsaMinor': 3.*units.Gyr,  'Willman1': 2.*units.Gyr}

unbound_dict = {'BootesI': 3.5*units.Gyr, 'Carina': 5.5*units.Gyr, 'ComaBerenices': 5.*units.Gyr,'Draco': 1.*units.Gyr,\
                'Fornax': 8.*units.Gyr,'ReticulumII': 1.5*units.Gyr,'Sgr': 1.*units.Gyr,'Sculptor': 5.*units.Gyr,\
                'Segue1': 2.*units.Gyr, 'Segue2': 1.5*units.Gyr,'TucanaIII': -5.5*units.Gyr, 'UrsaMajorII': 7.*units.Gyr,\
                'UrsaMinor': 3.*units.Gyr,  'Willman1': 0.5*units.Gyr}

xlim_dict = {'BootesI': '0,35', 'Carina': '20,47','ComaBerenices': '25,42.5','Draco': '30,80', 'Fornax': '18,29',\
             'ReticulumII': '10,22','Sgr': '20,70','Sculptor': '4,24', 'Segue1': '2,25', 'Segue2': '0,60',\
             'TucanaIII': '25,50', 'UrsaMajorII': '0,40', 'UrsaMinor': '3,7.5', 'Willman1': '10,30'}

ylim_dict = {'BootesI': '-50,20', 'Carina': '-60,25','ComaBerenices': '-4,4','Draco': '-30,40', 'Fornax': '8,17',\
             'ReticulumII': '0.5,4.5','Sgr': '-80,30','Sculptor': '-35,-5', 'Segue1': '-13,10',  'Segue2': '-50,70',\
             'TucanaIII': '-16,-10', 'UrsaMajorII': '-50,0', 'UrsaMinor': '-22,1', 'Willman1': '-50,50'}

pre_tform_dict = {'BootesI': 6.*units.Gyr, 'Carina': 5.*units.Gyr,'ComaBerenices': 5.*units.Gyr,'Draco': 5.*units.Gyr,\
                  'Fornax': 5.*units.Gyr, 'ReticulumII': 5.*units.Gyr, 'Sgr': 7.*units.Gyr, 'Sculptor': 5.*units.Gyr,\
                  'Segue1': 5.*units.Gyr, 'Segue2': 5.*units.Gyr, 'TucanaIII': 7.*units.Gyr,\
                  'UrsaMajorII': 5.*units.Gyr, 'UrsaMinor': 5.*units.Gyr, 'Willman1': 5.*units.Gyr}

post_tform_dict = {'BootesI': 4.9*units.Gyr, 'Carina': 5.*units.Gyr,'ComaBerenices': 5.*units.Gyr,'Draco': 4.3*units.Gyr,\
                   'Fornax': 5.*units.Gyr, 'ReticulumII': 5.*units.Gyr,'Sgr': 4.*units.Gyr,'Sculptor': 4.*units.Gyr, \
                   'Segue1': 4.3*units.Gyr,  'Segue2': 5.25*units.Gyr, 'TucanaIII': 4.8*units.Gyr,\
                   'UrsaMajorII': 4.5*units.Gyr, 'UrsaMinor': 5.*units.Gyr, 'Willman1': 5.*units.Gyr}







Bootes1:

In [10]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 1
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim, unbound_time = unboundt, pre_tform=6.*units.Gyr, post_tform=4.9*units.Gyr)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, end_strip=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, end_strip=unboundt,pre_tform=pre_tform, post_tform=post_tform)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 0.60987896,  0.55273659,  0.98813532, ...,  1.05715297,
          0.61883116,  1.22996913],
        [-0.35251953,  0.20780654,  0.53280074, ...,  0.54376059,
          0.3641706 ,  0.54561747],
        [ 0.56173048,  0.63038954,  0.33275475, ...,  0.31343274,
          0.54838652,  0.28218508],
        [-2.94514785, -3.48618902, -4.02969547, ..., -4.08202944,
         -3.63445953, -4.1957722 ],
        [-0.77847258, -0.60803752, -0.41276579, ..., -0.39482914,
         -0.55828468, -0.35017209],
        [-1.71302278, -0.80539824, -0.06380208, ..., -0.02367375,
         -0.52541972,  0.01421288]]),
 array([[ 0.60987896,  0.55273659,  1.6885769 , ...,  0.61883116,
          4.2813661 ,  1.22996913],
        [-0.35251953,  0.20780654, -0.12884315, ...,  0.3641706 ,
         -0.16143099,  0.54561747],
        [ 0.56173048,  0.63038954,  0.19202009, ...,  0.54838652,
          0.14907163,  0.28218508],
        [-2.94514785, -3.48618902, -0.06107605, ..., -3.63445953,
         -1.24

Notes: un-structured cocoon; seems to be some type of cocoon and doesn't have too much structure, slight cocoon around thin stream - fits cocoon prescription moderately well

Carina:

In [11]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 5
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 4.21812304,  4.27623831,  4.37444111,  4.27038537,  4.37275977,
          4.25638979,  4.3250775 ,  4.35768002,  4.35198339,  4.32128927,
          4.28490265,  4.38410957,  4.1999948 ,  4.22281907,  4.2677529 ,
          4.27127   ,  4.28892179,  4.33489132,  4.48935464,  4.19651743,
          4.27538758,  4.2793323 ,  4.27251688,  4.36177998,  4.45659461,
          4.41197855,  4.25938919,  4.50115473,  4.31819772,  4.37995157,
          4.3470201 ,  4.3936453 ,  4.47983508,  4.41750607,  4.28157643,
          4.35366124,  4.31648626,  4.54653743,  4.44218153,  4.30646921,
          4.22415524,  4.30401639,  4.39977509,  4.22767769,  4.29941587,
          4.38417523,  4.36955634,  4.45638577,  4.39042608,  4.41051423,
          4.27834841,  4.26724004,  4.1986159 ,  4.45804757,  4.49180831,
          4.37261688,  4.23897843,  4.20320908,  4.28812807,  4.30246475,
          4.30479609,  4.29862687,  4.41143887,  4.19744949,  4.45301572,
          4.19827746,  4.37642272,  4.

Notes: highly structured cocoon; doesn't seem to correspond well to a cocoon-like structure, stars seem to follow orbit of GC very tightly - does not fit cocoon prescription at all

ComaBerenices:

In [13]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 8
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 3.84735015,  3.70612106,  4.10554578, ...,  3.93573089,
          3.94980003,  4.02988204],
        [-0.58314137, -0.62594834, -0.50565025, ..., -0.55750972,
         -0.55844836, -0.5274188 ],
        [-0.11026014, -0.11213851, -0.09883679, ..., -0.10699657,
         -0.10721528, -0.10334928],
        [-0.35289007, -0.46508389, -0.14281126, ..., -0.30291466,
         -0.3295803 , -0.24712649],
        [-0.452606  , -0.44611092, -0.46404721, ..., -0.45404618,
         -0.4515092 , -0.45496225],
        [-2.86439848, -2.87389766, -2.87261085, ..., -2.8642714 ,
         -2.86662182, -2.86195025]]),
 array([[ 3.84735015,  3.70612106,  4.32772813, ...,  3.93573089,
          3.94980003,  4.02988204],
        [-0.58314137, -0.62594834, -0.40863717, ..., -0.55750972,
         -0.55844836, -0.5274188 ],
        [-0.11026014, -0.11213851, -0.09929797, ..., -0.10699657,
         -0.10721528, -0.10334928],
        [-0.35289007, -0.46508389,  0.30898064, ..., -0.30291466,
         -0.32

Notes: unstructured cocoon, seems to be a wide dispersion of stars around the thin stream - fits cocoon prescription well

Draco:

In [15]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 10
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 8.66867338,  8.90594853,  8.72940915,  8.7414789 ,  8.90302979,
          8.88749205,  8.59217153,  8.64524676,  8.60042667,  8.61023382,
          8.8462855 ,  8.69898013,  8.8805169 ,  8.70275243,  8.77530403,
          8.68344635,  8.64366303,  8.6201977 ,  8.60224557,  8.73836427,
          8.91924867,  8.80349999,  8.68196721,  8.7084665 ,  8.63562642,
          8.78933055,  8.64639025,  8.61206688,  8.94254552,  8.6426895 ,
          8.88792367,  8.81334531,  8.707862  ,  8.61272275,  8.81621091,
          8.83160729,  8.84117038,  8.80136205,  8.64877043,  8.60875934,
          8.93619508,  8.61266995,  8.86550948,  8.69097505,  8.8225766 ,
          8.65621868,  8.61790132,  8.59203561,  8.73454661,  8.81105936,
          8.67340862,  8.88951455,  8.7982732 ,  8.82426611,  8.5980759 ,
          8.78623804,  8.9222839 ,  8.85862078,  8.86546145,  8.61904235,
          8.92732686,  8.62365386,  8.6698207 ,  8.62361263,  8.59970998,
          8.58266493,  8.84277236,  8.

Notes: relatively structured cocoon, very slight cocoon around thin stream - doesn't fit cocoon prescription well

Fornax:

In [16]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 13
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 3.00092971,  3.00887591,  3.1060314 ,  3.24292813,  3.23079112,
          3.21006354,  3.40131228,  3.79773139,  3.37250346,  3.20638969,
          3.37786437,  3.17402785,  3.01978853,  3.07401864,  2.98761   ,
          3.169258  ,  3.91648869,  3.23709959,  3.21233985,  3.08900758,
          3.24298451,  3.52005438,  3.32001941,  3.64853291,  3.28675641,
          3.01245806,  3.06961014,  3.79911044,  3.31369737,  3.70371833,
          3.46985074,  3.68956535,  3.38656286,  3.25613524,  3.16229519,
          3.14237502,  3.12344603,  3.58798837,  3.42846486,  3.23901534,
          3.96459456,  3.45178587,  2.97356464,  3.22749251,  3.22839767,
          3.22402513,  3.02895085,  3.65142712,  3.17815311,  3.5345377 ,
          3.27268552,  3.41854572,  3.2874898 ,  3.05655061,  3.18233776,
          3.02299402,  3.23538824,  3.0972682 ,  3.16250383,  3.92507609,
          3.26109163,  3.01043155,  3.2133317 ,  3.62342447,  3.40600263,
          3.28254845,  3.48353612,  3.

Notes: structured cocoon but also strong cocoon surrounding thin stream - fits cocoon prescription well


ReticulumII:

In [17]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 26
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 2.15747292e+00,  2.83617500e+00,  2.94289902e+00,
          2.31516752e+00,  3.16878076e+00,  2.44380587e+00,
          3.03219167e+00,  2.08429340e+00,  2.53463978e+00,
          2.41261643e+00,  2.78049959e+00,  2.13801238e+00,
          2.45910071e+00,  2.20525554e+00,  2.92239170e+00,
          2.87932472e+00,  2.14286857e+00,  2.91495614e+00,
          2.90325571e+00,  2.61529169e+00,  2.64621595e+00,
          2.48862813e+00,  3.19375769e+00,  2.59847538e+00,
          2.50816994e+00,  2.47527078e+00,  2.32084506e+00,
          2.54381843e+00,  2.09584673e+00,  2.74396368e+00,
          2.43425567e+00,  2.39282344e+00,  3.06099365e+00,
          2.78846059e+00,  2.50551927e+00,  2.36122947e+00,
          2.24408194e+00,  2.03228371e+00,  2.25769408e+00,
          2.23851898e+00,  2.33079005e+00,  2.87527696e+00,
          2.05883932e+00,  2.61062375e+00,  2.35093526e+00,
          2.36759908e+00,  2.92094542e+00,  2.93439022e+00,
          2.72151601e+00,  2.92028294e+0

Notes: unstructured cocoon with a strong cocoon surrounding thin stream - fits cocoon prescription well

Sgr:

In [18]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 27
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 7.11474464,  6.77805836,  6.81687486, ...,  6.36576591,
          7.97447871,  6.804055  ],
        [-0.32551162, -0.39086215, -0.38567732, ..., -0.46534327,
         -0.16634894, -0.38621937],
        [ 0.23236899,  0.24174567,  0.24311409, ...,  0.25840178,
          0.21606783,  0.24120599],
        [-1.40280645, -0.91547638, -0.93337484, ..., -0.38569841,
         -2.6181288 , -0.95033506],
        [ 0.58015808,  0.5942914 ,  0.59579447, ...,  0.60520828,
          0.52387395,  0.59347374],
        [ 2.80756877,  2.83522564,  2.8341974 , ...,  2.87172122,
          2.75612705,  2.83311775]]),
 array([[  1.43668615,   7.11474464,   7.59574797, ...,   7.97447871,
           3.68335212,   6.804055  ],
        [ -0.34397365,  -0.32551162,   0.36290312, ...,  -0.16634894,
          -0.58384135,  -0.38621937],
        [ -0.1413143 ,   0.23236899,   0.14821181, ...,   0.21606783,
           0.09818603,   0.24120599],
        [-17.06688259,  -1.40280645,   2.66923935, ...,  -2.61

Notes: somewhat structured cocoon, slight cocoon surrounding thin stream - fits cocoon prescription somewhat well

Sculptor:

In [21]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 28
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 1.45304564,  1.18323417,  0.88212691,  1.63255403,  1.51880724,
          1.43980609,  0.99801854,  1.36821234,  1.4854996 ,  1.19127161,
          1.00006281,  1.54804873,  1.35390156,  1.57510888,  1.13328416,
          1.1461954 ,  1.61508043,  1.4782513 ,  1.51711438,  1.50589213,
          1.57010664,  1.57207089,  1.58146036,  1.51753228,  1.56788679,
          1.63083805,  1.15633285,  1.43108984,  1.5324291 ,  1.05057288,
          1.4504372 ,  1.4015991 ,  1.13472686,  1.47827301,  1.6433039 ,
          1.01731279,  1.53448109,  1.63051523,  1.05268823,  1.53938137,
          1.55396871,  1.30606431,  1.56836266,  1.49081465,  1.25184996,
          1.48647063,  1.62360614,  1.11325747,  1.05964087,  1.081396  ,
          1.28748142,  1.13635222,  1.50575998,  1.17490598,  0.96384443,
          1.34767387,  1.58168263,  1.22613292,  1.36267283,  1.19515106,
          1.5015088 ,  1.46990935,  1.53182892,  1.12481297,  1.59511301,
          0.94755176,  1.63569016,  1.

Notes: structured cocoon with slight cocoon surrounding thin stream - fits cocoon prescription well

Segue1:

In [22]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 29
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 0.8414712 ,  0.64757684,  0.78766426,  0.9203705 ,  0.69904865,
          1.5307249 ,  1.22602697,  0.51341269,  1.25366876,  0.52654397,
          0.78598584,  0.6419098 ,  0.72257635,  1.56249452,  1.39872216,
          1.36726733,  1.12474384,  1.08897492,  1.15506417,  1.157511  ,
          1.20920843,  0.84914731,  1.13044277,  0.47436761,  1.50537956,
          0.45660836,  0.91228277,  0.45847497,  1.50617653,  1.5478334 ,
          0.99538837,  1.6213989 ,  0.57148894,  0.95112755,  0.82169693,
          1.15440147,  0.76230669,  1.06620111,  1.28239625,  0.84093556,
          0.68468362,  0.80397532,  0.81015766,  1.3680737 ,  0.90089629,
          1.0496338 ,  0.4656228 ,  1.23852813,  1.45788034,  1.19454826,
          0.76959379,  0.61816293,  1.18012387,  1.42638154,  1.39369166,
          0.92108595,  1.08551242,  1.3030896 ,  1.4215793 ,  1.04092787,
          1.13699066,  0.47171162,  0.7863099 ,  0.90121743,  1.42330008,
          1.57831511,  0.89650816,  0.

Notes: unstructured cocoon, strong cocoon around thin stream - fits cocoon prescription very well

Segue2:

In [23]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 30
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 4.42287535,  4.69041923,  4.83119625,  4.44163674,  4.58621049,
          4.68622415,  4.83826204,  4.64849731,  4.7517428 ,  4.76152698,
          4.49695633,  4.87199173,  4.63852844,  4.7216987 ,  4.39613304,
          4.41591895,  4.51568606,  4.62119277,  4.62202237,  4.80910049,
          4.89637716,  4.51562945,  4.88188325,  4.86405387,  4.55374443,
          4.87160472,  5.05540543,  5.21247297,  4.7495738 ,  4.53780885,
          5.01667168,  4.68429795,  4.51413256,  4.50788838,  4.95942114,
          4.72342646,  4.70160448,  4.84965986,  4.59418278,  4.84493811,
          4.90937096,  4.98146509,  4.66614245,  4.47115812,  4.41308155,
          4.69972223,  4.82476913,  4.45852203,  4.44285537,  4.73802186,
          4.79684867,  4.8981149 ,  4.44702132,  4.44321041,  5.00333902,
          4.5258678 ,  4.39093974,  4.4303962 ,  4.48612156,  4.38954803,
          4.88760242,  4.89053106,  4.85586266,  4.6199848 ,  4.63215196,
          4.41533414,  4.58970926,  4.

Notes: structured cocoon, almost no cocoon surrounding thin stream - does not fit cocoon prescription well

TucanaIII:

In [24]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 35
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 6.32012684,  5.26027503,  5.0625151 , ...,  5.9528135 ,
          5.07571832,  5.38643508],
        [ 0.44635707,  0.64582094,  0.67578076, ...,  0.5224744 ,
          0.67454605,  0.6268871 ],
        [ 0.20602826,  0.24867357,  0.25306489, ...,  0.21890208,
          0.25591781,  0.24261568],
        [-1.03049751, -1.50350368, -1.57572407, ..., -1.24214484,
         -1.55407018, -1.49399121],
        [ 0.22842298,  0.16660919,  0.15147101, ...,  0.20789281,
          0.15704127,  0.16919773],
        [ 1.12437947,  1.04435128,  1.03526773, ...,  1.09572038,
          1.03369812,  1.03725106]]),
 array([[ 6.51329839,  6.32012684,  5.26027503, ...,  5.38643508,
          6.92557344,  2.6882479 ],
        [ 0.40670527,  0.44635707,  0.64582094, ...,  0.6268871 ,
         -0.04076281,  1.01223982],
        [ 0.18345962,  0.20602826,  0.24867357, ...,  0.24261568,
          0.1357195 ,  0.50279442],
        [-1.86490562, -1.03049751, -1.50350368, ..., -1.49399121,
         -2.53

Notes: unstructured cocoon, strong cocoon around thin stream - fits cocoon prescription well

UrsaMajorII:

In [25]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 37
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 2.02368769,  2.21595641,  2.22216236,  2.2835474 ,  2.05858529,
          2.48687776,  1.93034553,  2.59260907,  2.31271419,  2.41961335,
          2.42068593,  2.11859785,  2.09064078,  2.29767711,  2.38547455,
          1.92400746,  2.40648642,  2.24613734,  2.29719123,  3.4427912 ,
          2.07829139,  2.26350359,  1.92709823,  2.59206025,  2.13255268,
          1.92466709,  1.89205461,  2.22442689,  2.04114882,  2.48509006,
          1.9409563 ,  2.73031495,  2.90512935,  1.96376648,  1.93549199,
          1.94640468,  2.31785292,  2.36755639,  1.93844679,  2.48408166,
          2.1337884 ,  1.95558893,  2.35271463,  2.10401841,  1.9125373 ,
          2.24113613,  2.71914455,  1.97308043,  2.32839934,  1.88015967,
          2.15428085,  1.9191954 ,  2.08996241,  2.20609586,  2.36275296,
          2.1877898 ,  2.68552053,  2.20976595,  3.54010791,  2.03676658,
          2.08498631,  2.22033593,  2.35268757,  2.25515757,  2.12809865,
          2.32311641,  1.91918121,  2.

Notes: seems unstructured, cocoon around thin stream - fits cocoon prescription relatively well

UrsaMinor:

In [26]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 38
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 7.26311187e-01,  7.75598003e-01,  7.69906830e-01,
          7.18477843e-01,  4.30205494e-01,  7.20238184e-01,
          7.30203308e-01,  7.21330673e-01,  2.21490578e-01,
          6.67953267e-01,  7.91207352e-01,  7.47314408e-01,
          7.33214560e-01,  7.44944916e-01,  7.23830217e-01,
          7.73518962e-01,  7.96246642e-01,  6.58128216e-01,
          7.89517619e-01,  3.65355036e-01,  6.64794568e-01,
          7.93852998e-01,  7.05622780e-01,  6.79267772e-01,
          7.80153860e-01,  4.04171935e-01,  7.83501229e-01,
          3.86445741e-01,  6.63521024e-01,  7.79653695e-01,
          7.97805773e-01,  5.03948520e-01,  7.63282500e-01,
          7.03094322e-01,  6.25624355e-01,  6.56768676e-01,
          6.24606567e-01,  3.33330742e-01,  7.88917175e-01,
          7.82923981e-01,  7.37833041e-01,  7.71467731e-01,
          6.63921070e-01,  7.07290661e-01,  7.82103107e-01,
          7.02773696e-01,  6.84058164e-01,  7.74305938e-01,
          5.14114809e-01,  7.23197391e-0

Notes: somewhat structured, slight cocoon surrounding thin stream - fits cocoon prescription somewhat well

Willman1:

In [27]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 39
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster, xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform,unbound_time = unboundt)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform,pre_tform=pre_tform, post_tform=post_tform, end_strip=unboundt)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 1.85517473,  1.88250056,  1.84652653, ...,  1.81753139,
          1.86070316,  1.85434873],
        [ 0.15914509, -0.1825091 , -0.12400796, ..., -0.01922515,
         -0.17331764, -0.15961179],
        [ 0.69735599,  0.68802737,  0.70497087, ...,  0.71443915,
          0.692113  ,  0.6970388 ],
        [ 5.23743957,  4.73813417,  4.83216262, ...,  5.02780523,
          4.71455654,  4.76213856],
        [ 0.29137738,  0.46357964,  0.42865378, ...,  0.37754159,
          0.45923625,  0.44764485],
        [ 1.70677491,  1.13707257,  1.24105128, ...,  1.41139851,
          1.15541478,  1.1808152 ]]),
 array([[ 1.85517473,  1.95509778,  1.88250056, ...,  3.18290422,
          1.85434873,  2.24481927],
        [ 0.15914509, -0.21832346, -0.1825091 , ..., -0.36435781,
         -0.15961179, -0.35220582],
        [ 0.69735599,  0.68177183,  0.68802737, ...,  0.31724388,
          0.6970388 ,  0.57665398],
        [ 5.23743957,  4.62386663,  4.73813417, ..., -0.5966611 ,
          4.76

Notes: slightly strucutured cocoon, very little cocoon surrounding thin stream - doesn't fit cocoon prescription well

# Meeting with Jo - Aug 19, 2020

In [4]:
index_list = [29, 35, 37, 38] # focus on these 4, display some interesting features

# Run function to plot tidalstreams and save plots 
for counter, index in enumerate(index_list):
    sat = satellite_gal[index]
    sat_name = name_satellite_gal[index]
    tform = tform_dict[sat_name]
    unboundt = unbound_dict[sat_name]
    post_tform = post_tform_dict[sat_name]
    pre_tform = pre_tform_dict[sat_name]
    
    xlims = xlim_dict[sat_name].split(',')
    xlim = (float(xlims[0]), float(xlims[1]))
    ylims = ylim_dict[sat_name].split(',')
    ylim = (float(ylims[0]), float(ylims[1]))
    
    RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
    =plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,\
                       post_tform = post_tform, unbound_time = unboundt,xlim=xlim, ylim=ylim)
    test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, end_strip=unboundt)
    test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, end_strip=unboundt)
    tstart = tform - pre_tform
    tend = tform + post_tform
    plot_colormap(cluster_orbit, cluster_orbitb, tstart, tend, RvR, RvRt, dt, dtt, xlim, ylim,sat_name)
    

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …