In [1]:
%matplotlib widget
import matplotlib.pyplot as plt
import numpy 
from interactive_modelstreams import plot_tidalstreams, zoom, plot_colormap, test_cocoon, test_stream
from clusterorbits import plot_sat_cluster
from galpy.orbit import Orbit
from galpy.potential import HernquistPotential
from astropy import units

# Import orbits for Milky Way's satellite galaxies
satellite_gal = Orbit.from_name('MWsatellitegalaxies') #list of satellite galaxies of Milky Way 
name_satellite_gal = satellite_gal.name

gzip was not found on your system! You should solve this issue for astroquery.eso to be at its best!
On POSIX system: make sure gzip is installed and in your path!On Windows: same for 7-zip (http://www.7-zip.org)!


After each satellite galaxy's tidal streams are plotted and test_cocoon + test_stream are both run on simulations, notes on the presence of a cocoon and if present, how well the cocoon matches expectations (based on GD-1) have been added in text below each code block. 

In [2]:
#Defining global properties for all 14 satellite galaxy simulations 

xaxis = 't'
yaxis = 'r'
Msat = 10.**11.*units.Msun
size = 1.05*(Msat/(10.**8./1*units.Msun))**0.5*units.kpc
potential = HernquistPotential(amp = 2*Msat, a = size, ro = 8., vo=220.)
x,y,z = 4*units.kpc, 0*units.kpc, 0*units.kpc
vcirc = potential.vcirc(4*units.kpc)
vx, vy, vz = 0.*units.km/units.s, vcirc, 0.*units.km/units.s
#tform, tsteady = 7.*units.Gyr, 0.5*units.Gyr 
    #timescale for tidal disruption of satellite galaxy
Mcluster = 2e4*units.Msun

index_list = [1,5,8,10,13,26,27,28,29,30,35,37,38,39]
tsteady = 0.5*units.Gyr

# Define dictionaries for tform, unbound time, xlim, ylim, pre_tform and post_tform for all 14 satellite galaxies

tform_dict = {'BootesI': 6.*units.Gyr, 'Carina': 5.*units.Gyr,'ComaBerenices': 6.*units.Gyr,  'Draco': 0.*units.Gyr,\
              'Fornax': 8.*units.Gyr, 'ReticulumII': 2.*units.Gyr, 'Sgr': 4.*units.Gyr, 'Sculptor': 5.*units.Gyr,\
              'Segue1': 2.*units.Gyr, 'Segue2': 1.5*units.Gyr, 'TucanaIII': -3.*units.Gyr, 'UrsaMajorII': 6.5*units.Gyr,\
              'UrsaMinor': 3.*units.Gyr,  'Willman1': 2.*units.Gyr}

unbound_dict = {'BootesI': 3.5*units.Gyr, 'Carina': 5.5*units.Gyr, 'ComaBerenices': 5.*units.Gyr,'Draco': 1.*units.Gyr,\
                'Fornax': 8.*units.Gyr,'ReticulumII': 1.5*units.Gyr,'Sgr': 1.*units.Gyr,'Sculptor': 5.*units.Gyr,\
                'Segue1': 2.*units.Gyr, 'Segue2': 1.5*units.Gyr,'TucanaIII': -5.5*units.Gyr, 'UrsaMajorII': 7.*units.Gyr,\
                'UrsaMinor': 3.*units.Gyr,  'Willman1': 0.5*units.Gyr}

xlim_dict = {'BootesI': '0,35', 'Carina': '20,47','ComaBerenices': '25,42.5','Draco': '30,80', 'Fornax': '18,29',\
             'ReticulumII': '10,22','Sgr': '20,70','Sculptor': '4,24', 'Segue1': '2,25', 'Segue2': '0,60',\
             'TucanaIII': '25,50', 'UrsaMajorII': '0,40', 'UrsaMinor': '3,7.5', 'Willman1': '10,30'}

ylim_dict = {'BootesI': '-50,20', 'Carina': '-60,25','ComaBerenices': '-4,4','Draco': '-30,40', 'Fornax': '8,17',\
             'ReticulumII': '0.5,4.5','Sgr': '-80,30','Sculptor': '-35,-5', 'Segue1': '-13,10',  'Segue2': '-50,70',\
             'TucanaIII': '-16,-10', 'UrsaMajorII': '-50,0', 'UrsaMinor': '-22,1', 'Willman1': '-50,50'}

pre_tform_dict = {'BootesI': 6.*units.Gyr, 'Carina': 5.*units.Gyr,'ComaBerenices': 5.*units.Gyr,'Draco': 5.*units.Gyr,\
                  'Fornax': 5.*units.Gyr, 'ReticulumII': 5.*units.Gyr, 'Sgr': 7.*units.Gyr, 'Sculptor': 5.*units.Gyr,\
                  'Segue1': 5.*units.Gyr, 'Segue2': 5.*units.Gyr, 'TucanaIII': 7.*units.Gyr,\
                  'UrsaMajorII': 5.*units.Gyr, 'UrsaMinor': 5.*units.Gyr, 'Willman1': 5.*units.Gyr}

post_tform_dict = {'BootesI': 4.9*units.Gyr, 'Carina': 5.*units.Gyr,'ComaBerenices': 5.*units.Gyr,'Draco': 4.3*units.Gyr,\
                   'Fornax': 5.*units.Gyr, 'ReticulumII': 5.*units.Gyr,'Sgr': 4.*units.Gyr,'Sculptor': 4.*units.Gyr, \
                   'Segue1': 4.3*units.Gyr,  'Segue2': 5.25*units.Gyr, 'TucanaIII': 4.8*units.Gyr,\
                   'UrsaMajorII': 4.5*units.Gyr, 'UrsaMinor': 5.*units.Gyr, 'Willman1': 5.*units.Gyr}







Bootes1:

In [3]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 1
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim, pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 5.99664357e-01,  1.72809088e+00,  8.34414797e-01, ...,
          1.11713576e+00,  6.39514123e-01,  5.81044044e-01],
        [-3.27237423e-01,  5.41659749e-01,  5.00439872e-01, ...,
          5.47241568e-01,  3.96949298e-01, -3.48613455e-01],
        [ 5.74522828e-01,  1.95024646e-01,  3.96814700e-01, ...,
          3.00697638e-01,  5.19428266e-01,  5.79053083e-01],
        [-2.98738725e+00, -4.41160366e+00, -3.89901536e+00, ...,
         -4.11620381e+00, -3.67660816e+00, -2.93720203e+00],
        [-7.67871631e-01, -2.12726809e-01, -4.65996086e-01, ...,
         -3.78515752e-01, -5.42038455e-01, -7.71199954e-01],
        [-1.67151310e+00,  1.87500881e-01, -1.86035420e-01, ...,
         -2.43236803e-03, -4.48812999e-01, -1.68135367e+00]]),
 array([[ 0.59966436,  1.72809088,  1.99923968, ...,  1.34999338,
          0.77753893,  0.58104404],
        [-0.32723742,  0.54165975,  0.48838804, ..., -0.4747328 ,
          0.56384132, -0.34861345],
        [ 0.57452283,  0.19502465,  0.

Notes: un-structured cocoon; seems to be some type of cocoon and doesn't have too much structure, slight cocoon around thin stream - fits cocoon prescription moderately well

Carina:

In [4]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 5
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 4.36052835,  4.31862724,  4.35083624,  4.33392913,  4.41757642,
          4.26005074,  4.2896654 ,  4.53824954,  4.53108432,  4.25387404,
          4.23228317,  4.2722755 ,  4.28908647,  4.20328316,  4.39102398,
          4.3782728 ,  4.3187628 ,  4.26878763,  4.20016325,  4.36149309,
          4.4034029 ,  4.29849225,  4.34323694,  4.3568723 ,  4.22109279,
          4.30174418,  4.48112698,  4.22321117,  4.36314547,  4.34785811,
          4.32612173,  4.45603969,  4.24066021,  4.19500788,  4.33607856,
          4.27338909,  4.31951977,  4.2347424 ,  4.46873284,  4.270237  ,
          4.2107539 ,  4.25828451,  4.27865285,  4.2004422 ,  4.40427953,
          4.27645873,  4.28838215,  4.30868244,  4.28524744,  4.28613128,
          4.19714794,  4.50185921,  4.34559992,  4.45013876,  4.30248938,
          4.45532913,  4.20819711,  4.41216966,  4.30223256,  4.2721289 ,
          4.24588692,  4.33203703,  4.2224564 ,  4.25867483,  4.36127869,
          4.33338663,  4.27434577,  4.

Notes: highly structured cocoon; doesn't seem to correspond well to a cocoon-like structure, stars seem to follow orbit of GC very tightly - does not fit cocoon prescription at all

ComaBerenices:

In [5]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 8
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 4.05178415,  4.29864047,  3.8412329 , ...,  3.95674945,
          4.30685624,  4.10956552],
        [-0.51580668, -0.44491634, -0.58532942, ..., -0.55346698,
         -0.4394854 , -0.50531537],
        [-0.10375437, -0.09798807, -0.10948137, ..., -0.10744692,
         -0.09658075, -0.10083447],
        [-0.21142366, -0.01235184, -0.3927191 , ..., -0.3094853 ,
          0.02661342, -0.19400349],
        [-0.45678286, -0.46024486, -0.44872821, ..., -0.45242633,
         -0.46324841, -0.45682346],
        [-2.86037919, -2.85311961, -2.87109981, ..., -2.86644337,
         -2.8548837 , -2.86656985]]),
 array([[ 4.05178415,  4.29864047,  3.0564965 , ...,  0.5157669 ,
          4.30685624,  4.10956552],
        [-0.51580668, -0.44491634, -0.80842151, ...,  1.30404142,
         -0.4394854 , -0.50531537],
        [-0.10375437, -0.09798807, -0.09919285, ..., -0.22837334,
         -0.09658075, -0.10083447],
        [-0.21142366, -0.01235184, -1.08654572, ..., -1.22002999,
          0.02

Notes: unstructured cocoon, seems to be a wide dispersion of stars around the thin stream - fits cocoon prescription well

Draco:

In [6]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 10
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 8.88051865,  8.80860266,  8.7450563 ,  8.62623843,  8.85227167,
          8.73609564,  8.83181685,  8.63337715,  8.6835168 ,  8.69601679,
          8.74861599,  8.90003594,  8.83259115,  8.60287938,  8.80002753,
          8.69294265,  8.63747408,  8.67831643,  8.73299677,  8.90021509,
          8.83976409,  8.90056979,  8.81257429,  8.68499742,  8.69094904,
          8.84016042,  8.85137985,  8.82330508,  8.62701425,  8.70377247,
          8.61503723,  8.7675138 ,  8.84886061,  8.6391416 ,  8.85863056,
          8.60909942,  8.95759808,  8.62704545,  8.8560659 ,  8.67044312,
          8.86203539,  8.60837562,  8.80332446,  8.61782276,  8.7557498 ,
          8.62591427,  8.83927744,  8.66108177,  8.7233253 ,  8.60088938,
          8.66419309,  8.67305781,  8.86517535,  8.83387953,  8.61881453,
          8.8095156 ,  8.78110293,  9.00602943,  8.96732909,  8.76086308,
          8.70863145,  8.78913248,  8.68531377,  8.73482325,  8.83753587,
          8.80335671,  8.67101044,  8.

Notes: relatively structured cocoon, very slight cocoon around thin stream - doesn't fit cocoon prescription well

Fornax:

In [7]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 13
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 3.05790034,  3.02050066,  3.46054346, ...,  3.75700142,
          3.28220382,  3.23789918],
        [ 0.61839295,  0.6292246 ,  0.47888364, ...,  0.3498417 ,
          0.54774679,  0.56397184],
        [-0.19805632, -0.20207119, -0.17511108, ..., -0.16308187,
         -0.18492067, -0.18721746],
        [ 1.43954474,  1.47760207,  1.00617837, ...,  0.55674797,
          1.22766024,  1.2833629 ],
        [-0.54874647, -0.54353672, -0.61003112, ..., -0.63971877,
         -0.5830155 , -0.57539662],
        [ 1.62906213,  1.63220388,  1.58688356, ...,  1.55777856,
          1.60547254,  1.60927077]]),
 array([[ 2.58110158,  3.05790034,  4.01364792, ...,  3.6064815 ,
          1.25970751,  3.12640329],
        [ 0.691035  ,  0.61839295,  0.10824451, ...,  0.42545408,
          0.88828336,  0.50628469],
        [-0.34847089, -0.19805632, -0.15450249, ..., -0.17099724,
         -0.4077672 , -0.29101074],
        [ 1.42165485,  1.43954474, -0.43524081, ...,  0.80845476,
          2.59

Notes: structured cocoon but also strong cocoon surrounding thin stream - fits cocoon prescription well


ReticulumII:

In [8]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 26
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 2.08079330e+00,  2.65197550e+00,  2.88056556e+00,
          2.20332769e+00,  3.30141813e+00,  2.13452953e+00,
          2.79536437e+00,  2.05442183e+00,  2.91511361e+00,
          2.98609779e+00,  2.53510659e+00,  2.58881310e+00,
          2.90250961e+00,  2.07065314e+00,  3.06056102e+00,
          2.44997249e+00,  2.67630493e+00,  2.39912390e+00,
          2.54435597e+00,  2.59581280e+00,  2.79268721e+00,
          2.43493011e+00,  2.90217832e+00,  2.20274835e+00,
          2.99524024e+00,  2.16726106e+00,  2.78279306e+00,
          2.39592407e+00,  2.98286736e+00,  2.07722311e+00,
          2.63540730e+00,  2.53590745e+00,  2.71266831e+00,
          3.09930702e+00,  2.35116636e+00,  2.74028208e+00,
          2.76609073e+00,  2.93015128e+00,  2.34189192e+00,
          2.13709056e+00,  2.97561362e+00,  2.34326338e+00,
          2.98040790e+00,  2.67522810e+00,  2.24787794e+00,
          2.95746179e+00,  2.21603341e+00,  2.16621471e+00,
          2.90499099e+00,  2.46942063e+0

Notes: unstructured cocoon with a strong cocoon surrounding thin stream - fits cocoon prescription well

Sgr:

In [9]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 27
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 6.87054178,  7.20229634,  6.52201681, ...,  6.13675298,
          7.1570444 ,  6.95358006],
        [-0.37657951, -0.31251774, -0.43911133, ..., -0.50379704,
         -0.32029876, -0.34933205],
        [ 0.24116441,  0.23111129,  0.2533316 , ...,  0.26929503,
          0.23237295,  0.2374527 ],
        [-1.00659617, -1.52673068, -0.5433348 , ..., -0.09435527,
         -1.47396612, -1.20428173],
        [ 0.59190236,  0.57840385,  0.60143653, ...,  0.60747473,
          0.58091064,  0.58806047],
        [ 2.8279506 ,  2.80062087,  2.85837346, ...,  2.88869679,
          2.80325075,  2.81876853]]),
 array([[ 6.87054178,  7.20229634,  6.52201681, ...,  6.95358006,
          2.2778598 ,  5.37246428],
        [-0.37657951, -0.31251774, -0.43911133, ..., -0.34933205,
          0.95525572, -0.19494717],
        [ 0.24116441,  0.23111129,  0.2533316 , ...,  0.2374527 ,
          0.14561771,  0.05867379],
        [-1.00659617, -1.52673068, -0.5433348 , ..., -1.20428173,
          0.31

Notes: somewhat structured cocoon, slight cocoon surrounding thin stream - fits cocoon prescription somewhat well

Sculptor:

In [10]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 28
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 1.58630972,  1.57721767,  0.96557202,  1.45867188,  1.60294697,
          1.22851526,  1.61542158,  0.90903799,  1.14676683,  1.13590948,
          1.07425494,  1.3608109 ,  1.40009132,  1.43710085,  0.99307894,
          1.57757426,  1.29795885,  1.18360859,  1.61418747,  0.97876338,
          1.55959442,  0.94987031,  1.56453211,  1.44074057,  1.56675864,
          1.58466598,  1.36679115,  1.0422518 ,  1.37073405,  1.08229444,
          1.59511446,  1.45272772,  1.32994953,  1.47507697,  1.26082581,
          1.06352058,  1.05540706,  1.57854801,  1.10460588,  1.51680788,
          1.47424822,  1.41975396,  1.32462647,  1.16107848,  1.33380917,
          1.62058721,  1.51347218,  1.352825  ,  1.37771439,  1.58829519,
          1.14173224,  1.61598182,  1.43358554,  1.31108378,  1.18579395,
          0.79289555,  1.11566463,  1.40661769,  1.59741765,  1.25185389,
          1.10815404,  1.42195715,  1.36816184,  1.30560968,  1.32863627,
          1.33789807,  1.45940206,  1.

Notes: structured cocoon with slight cocoon surrounding thin stream - fits cocoon prescription well

Segue1:

In [11]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 29
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 4.91916157e-01,  1.09406616e+00,  9.49254692e-01,
          1.23985217e+00,  8.94343879e-01,  5.63865557e-01,
          1.60771217e+00,  8.18183171e-01,  1.43823527e+00,
          1.40689761e+00,  9.40160289e-01,  9.99851626e-01,
          7.24062456e-01,  4.57139298e-01,  4.62793294e-01,
          1.06706688e+00,  6.97680181e-01,  1.00395859e+00,
          1.29633104e+00,  4.63584610e-01,  1.36207061e+00,
          4.71647785e-01,  7.10513545e-01,  1.33242281e+00,
          1.39539051e+00,  1.39025028e+00,  8.97081573e-01,
          7.34366530e-01,  1.20986371e+00,  1.25586373e+00,
          6.12820312e-01,  1.40031709e+00,  7.78909898e-01,
          1.26807345e+00,  1.02529245e+00,  5.32033680e-01,
          6.88827832e-01,  1.35906899e+00,  1.57502592e+00,
          6.75471066e-01,  7.55858946e-01,  7.91233503e-01,
          4.65806339e-01,  1.22078025e+00,  9.94635703e-01,
          1.16113432e+00,  6.50022376e-01,  1.35398047e+00,
          1.14200847e+00,  5.01591421e-0

Notes: unstructured cocoon, strong cocoon around thin stream - fits cocoon prescription very well

Segue2:

In [12]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 30
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 4.62812141,  4.81057489,  4.59300262,  4.57902843,  4.58642105,
          4.86032317,  4.39856771,  4.42569478,  4.42040765,  5.04850638,
          4.53322218,  4.76607249,  4.90497   ,  5.02438106,  4.61804788,
          4.38334083,  4.96447925,  4.39594185,  4.59937873,  4.97691909,
          4.63876199,  4.40709434,  4.70258112,  4.76753963,  4.3003778 ,
          4.7720633 ,  4.47011611,  4.46071879,  4.78258677,  4.50095918,
          4.42163356,  4.79117694,  5.01076527,  4.42710943,  4.43975006,
          4.75273713,  5.10927158,  4.78687976,  4.51676451,  5.01663897,
          4.74201711,  4.85676997,  4.51362912,  4.69532022,  4.63660185,
          4.75982258,  4.56881398,  4.40307026,  4.66777487,  4.56690065,
          4.73460206,  4.82779117,  4.68756167,  4.80184267,  5.08288338,
          5.00674375,  5.02461275,  4.54383311,  4.71693223,  4.48948674,
          4.77533891,  4.55750257,  4.54763811,  4.5976831 ,  4.54752599,
          4.40590973,  4.88217827,  4.

Notes: structured cocoon, almost no cocoon surrounding thin stream - does not fit cocoon prescription well

TucanaIII:

In [13]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 35
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 5.15086284,  5.28726929,  5.3522718 , ...,  4.86909768,
          5.26107837,  4.79311245],
        [ 0.66069507,  0.63715301,  0.63219332, ...,  0.7089392 ,
          0.6410889 ,  0.71561856],
        [ 0.25073048,  0.24589951,  0.24427173, ...,  0.27294852,
          0.24685354,  0.27182926],
        [-1.54745282, -1.4745366 , -1.48077543, ..., -1.57062611,
         -1.48508743, -1.60003197],
        [ 0.15806585,  0.16980946,  0.17172093, ...,  0.14853751,
          0.16987528,  0.14192721],
        [ 1.03741617,  1.04931955,  1.04366614, ...,  1.01337818,
          1.04882249,  1.01419935]]),
 array([[ 1.35967408,  6.61716196,  5.15086284, ...,  4.86909768,
          5.26107837,  4.79311245],
        [-0.57627331,  0.38996876,  0.66069507, ...,  0.7089392 ,
          0.6410889 ,  0.71561856],
        [ 0.14120388,  0.18490802,  0.25073048, ...,  0.27294852,
          0.24685354,  0.27182926],
        [ 2.10516688, -1.55259164, -1.54745282, ..., -1.57062611,
         -1.48

Notes: unstructured cocoon, strong cocoon around thin stream - fits cocoon prescription well

UrsaMajorII:

In [14]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 37
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 2.84410322,  2.11017119,  2.17153443,  2.12214001,  2.16067466,
          1.94432035,  2.12827153,  2.0480088 ,  2.16245146,  2.0798888 ,
          2.59486912,  2.35216993,  1.99730093,  2.48433718,  2.43858148,
          2.07923504,  2.37784524,  2.04058234,  1.90816303,  1.87589758,
          2.31669663,  2.05895448,  2.59568732,  2.14892088,  2.08437237,
          2.29546497,  2.17284831,  1.9197182 ,  2.36552383,  1.97997317,
          2.38417965,  2.06452418,  2.39475534,  2.43479671,  1.92624035,
          2.09602711,  2.63556903,  2.01462506,  2.43133907,  1.94057553,
          2.401652  ,  1.94873474,  2.25223042,  1.93688622,  2.33221749,
          2.12655426,  2.83452884,  2.46677745,  1.92812483,  1.93762732,
          2.21258952,  2.40834328,  2.59186114,  2.16934334,  1.8931983 ,
          2.51390502,  2.19585615,  1.91939242,  1.87257844,  2.12415787,
          1.94846858,  1.93380553,  2.04858765,  2.01162491,  2.31053013,
          1.86886306,  2.08519169,  2.

Notes: seems unstructured, cocoon around thin stream - fits cocoon prescription relatively well

UrsaMinor:

In [15]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 38
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 1.58694652e-01,  7.96548341e-01,  7.70598138e-01,
          7.38734747e-01,  7.85285358e-01,  7.93800403e-01,
          7.56722515e-01,  7.11088101e-01,  7.92311815e-01,
          7.08905038e-01,  3.90053385e-01,  7.66376871e-01,
          7.76572031e-01,  7.86712444e-01,  7.06216544e-01,
          7.48991740e-01,  7.85104661e-01,  7.59890565e-01,
          7.79433575e-01,  7.47148310e-01,  7.02550202e-01,
          6.86672479e-01,  7.35498633e-01,  7.89178769e-01,
          7.69802673e-01,  7.98579242e-01,  5.77477624e-01,
          7.55864875e-01,  7.94503415e-01,  7.48489268e-01,
          6.09461280e-01,  7.17720944e-01,  5.54187652e-01,
          2.11739160e-01,  7.30637499e-01,  7.34750517e-01,
          7.93819333e-01,  7.61799141e-01,  7.84228686e-01,
          7.93257066e-01,  6.94741776e-01,  7.02294960e-01,
          7.79216270e-01,  7.50157254e-01,  7.95814076e-01,
          7.94417785e-01,  7.46858988e-01,  6.60228455e-01,
          7.14080730e-01,  7.36220913e-0

Notes: somewhat structured, slight cocoon surrounding thin stream - fits cocoon prescription somewhat well

Willman1:

In [16]:
# Plot cluster orbit, stripping for total time, stripping before unbound time 
index = 39
sat = satellite_gal[index]
sat_name = name_satellite_gal[index]
tform = tform_dict[sat_name]
unboundt = unbound_dict[sat_name]
pre_tform = pre_tform_dict[sat_name]
post_tform = post_tform_dict[sat_name]

xlims = xlim_dict[sat_name].split(',')
xlim = (float(xlims[0]), float(xlims[1]))
ylims = ylim_dict[sat_name].split(',')
ylim = (float(ylims[0]), float(ylims[1]))

RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
=plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

# Test cocoon and stream
test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([[ 1.85230015,  1.81537651,  1.8130485 , ...,  1.83793866,
          1.80208365,  1.80193371],
        [-0.11093715, -0.00773239,  0.03692767, ..., -0.16790352,
         -0.05294808,  0.00531184],
        [ 0.70761523,  0.71452643,  0.71430766, ...,  0.69596172,
          0.72036903,  0.71803556],
        [ 4.86126131,  5.02959384,  5.10418762, ...,  4.69446855,
          4.8832918 ,  5.03512074],
        [ 0.42302396,  0.37143758,  0.34827632, ...,  0.45787845,
          0.39076742,  0.36559734],
        [ 1.25889196,  1.43033585,  1.50559169, ...,  1.16968027,
          1.35729804,  1.45334112]]),
 array([[ 1.85230015,  1.81537651,  1.8130485 , ...,  1.80208365,
          1.80193371,  2.1941709 ],
        [-0.11093715, -0.00773239,  0.03692767, ..., -0.05294808,
          0.00531184, -0.34067268],
        [ 0.70761523,  0.71452643,  0.71430766, ...,  0.72036903,
          0.71803556,  0.59017299],
        [ 4.86126131,  5.02959384,  5.10418762, ...,  4.8832918 ,
          5.03

Notes: slightly strucutured cocoon, very little cocoon surrounding thin stream - doesn't fit cocoon prescription well

# Meeting with Jo - Aug 19, 2020

In [17]:
index_list = [29, 35, 37, 38] # focus on these 4, display some interesting features

# Run function to plot tidalstreams and save plots 
for counter, index in enumerate(index_list):
    sat = satellite_gal[index]
    sat_name = name_satellite_gal[index]
    tform = tform_dict[sat_name]
    unboundt = unbound_dict[sat_name]
    post_tform = post_tform_dict[sat_name]
    pre_tform = pre_tform_dict[sat_name]
    
    xlims = xlim_dict[sat_name].split(',')
    xlim = (float(xlims[0]), float(xlims[1]))
    ylims = ylim_dict[sat_name].split(',')
    ylim = (float(ylims[0]), float(ylims[1]))
    
    RvR, RvRt, dt, dtt, cluster_orbit, cluster_orbitb\
    =plot_tidalstreams(sat, sat_name, potential,xaxis, yaxis, Msat, size, x,y,z,vx,vy,vz,tform,tsteady, Mcluster,xlim=xlim, ylim=ylim,pre_tform=pre_tform, post_tform=post_tform)

    # Test cocoon and stream
    test_cocoon(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
    test_stream(cluster_orbit, cluster_orbitb, RvR, RvRt, dt, dtt, xlim, ylim, sat_name,tform, unboundt=unboundt,pre_tform=pre_tform, post_tform=post_tform)
    tstart = tform - pre_tform
    tend = tform + post_tform
    plot_colormap(cluster_orbit, cluster_orbitb, tstart, tend, RvR, RvRt, dt, dtt, xlim, ylim,sat_name)
    

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\yumna\miniconda3\lib\site-packages\galpy\util\bovy_plot.py:284: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  elif not overplot and not gcf: pyplot.figure()



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …